plugins:
  - jekyll-relative-links
  - name: Generated Markdown Readmes
  uses: DaanV2/Markdown-Action-Create-Indexes@v2.0.0
  with: 
    folder: ${{github.workspace}}
    filename: index.md
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
