on: [push]
jobs:
  create-indexes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DaanV2/Markdown-Action-Create-Indexes@v2.0.0
        with:
          folder: ${{ github.workspace }}/
